version: 2

sources:
  - name: staging
    database: dbw_carrental_dev_7405614156846449
    schema: curated
    tables:
      - name: cars
      - name: have_optional
      - name: drivers
      - name: rentals
      - name: rental_offices
      - name: drive
      - name: insurances
      - name: payments
